[package]
name = "redo"
version = "0.41.0"
authors = ["evenorog <evenorog@gmail.com>"]
description = "High-level undo-redo functionality."
documentation = "https://docs.rs/redo"
repository = "https://github.com/evenorog/redo"
readme = "README.md"
license = "MIT OR Apache-2.0"
keywords = ["undo", "redo"]
categories = ["data-structures", "rust-patterns", "no-std"]
exclude = ["/.travis.yml"]
edition = "2018"

[dependencies]
undo = "0.42.0"

[badges]
travis-ci = { repository = "evenorog/redo" }
maintenance = { status = "actively-developed" }

[package.metadata.docs.rs]
features = ["chrono", "colored", "serde"]
