[package]
name = "redo"
version = "0.37.1"
authors = ["evenorog <evenorog@gmail.com>"]
description = "Provides undo-redo functionality with static dispatch and manual command merging."
documentation = "https://docs.rs/redo"
repository = "https://github.com/evenorog/redo"
readme = "README.md"
license = "MIT/Apache-2.0"
keywords = ["undo", "redo"]
categories = ["data-structures", "rust-patterns"]
exclude = ["/.travis.yml", "/redo.svg"]
edition = "2018"

[dependencies]
chrono = { version = "0.4.9", optional = true, features = ["serde"] }
colored = { version = "1", optional = true }
rustc-hash = "1"
serde = { version = "1", optional = true, features = ["derive"] }

[features]
default = []
display = ["colored"]

[badges]
travis-ci = { repository = "evenorog/redo" }
maintenance = { status = "actively-developed" }

[package.metadata.docs.rs]
features = ["chrono", "display", "serde"]
